# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import mptt.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSendgrid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('email', models.CharField(max_length=255, verbose_name='email')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('event', models.CharField(max_length=32, verbose_name='event type')),
                ('reason', models.CharField(default='', max_length=255, verbose_name='reason')),
                ('categories', models.CharField(blank=True, max_length=255, null=True, verbose_name='SendGrid Categories')),
                ('sg_message_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='SendGrid Message Id')),
                ('timestamp', models.CharField(blank=True, max_length=255, null=True, verbose_name='SendGrid Timestamp')),
                ('smtp_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='SendGrid SMTP Id')),
                ('ip', models.CharField(blank=True, max_length=255, null=True, verbose_name='SendGrid IP')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ssendgrid.EmailSendgrid')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
            },
        ),
    ]
