# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssendgrid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsendgrid',
            name='categories',
            field=models.CharField(blank=True, max_length=255, verbose_name='SendGrid Categories'),
        ),
        migrations.AddField(
            model_name='emailsendgrid',
            name='ip',
            field=models.CharField(blank=True, max_length=255, verbose_name='SendGrid IP'),
        ),
        migrations.AddField(
            model_name='emailsendgrid',
            name='sg_message_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='SendGrid Message Id'),
        ),
        migrations.AddField(
            model_name='emailsendgrid',
            name='smtp_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='SendGrid SMTP Id'),
        ),
        migrations.AddField(
            model_name='emailsendgrid',
            name='timestamp',
            field=models.CharField(blank=True, max_length=255, verbose_name='SendGrid Timestamp'),
        ),
    ]
